### PR TITLE
fix: repeat include causing compilation failed

### PR DESCRIPTION
**Pull request by CitrusSin**
图片
如题，在 arch linux 上编译失败，遂进行一个修补

### CODE REVIEW

**Review by fwhwf — COMMENTED** [review]
good

**Comment by ShelpAm** [comment]
The error is because disorder of `#include`s of `glad.h` and `GLFW/glfw3.h`.

Maybe a better way is to follow [GLFW's official site](https://www.glfw.org/docs/latest/quick.html), which tells the approach to solving the problem.

> To make sure there will be no header conflicts, you can define [GLFW_INCLUDE_NONE](https://www.glfw.org/docs/latest/build_guide.html#GLFW_INCLUDE_NONE) before the GLFW header to explicitly disable inclusion of the development environment header. This also allows the two headers to be included in any order.
> ```cpp
> #define GLFW_INCLUDE_NONE
> #include <GLFW/glfw3.h>
> #include <glad/gl.h>
> ```

I think we can adopt this approach. And based on this, in order not to manually define `GLFW_INCLUDE_NONE`, I think the following is better:
```cpp
// glfw.h
#pragma once

#ifndef GLFW_INCLUDE_NONE
#define GLFW_INCLUDE_NONE
#endif

#include <GLFW/glfw3.h>
```
It creates a new file named `glfw.h` to handle the problem.

**Comment by ShelpAm** [comment]
> The error is because disorder of `#include`s of `glad.h` and `GLFW/glfw3.h`.
> 
> Maybe a better way is to follow [GLFW's official site](https://www.glfw.org/docs/latest/quick.html), which tells the approach to solving the problem.
> 
> > To make sure there will be no header conflicts, you can define [GLFW_INCLUDE_NONE](https://www.glfw.org/docs/latest/build_guide.html#GLFW_INCLUDE_NONE) before the GLFW header to explicitly disable inclusion of the development environment header. This also allows the two headers to be included in any order.
> > ```c++
> > #define GLFW_INCLUDE_NONE
> > #include <GLFW/glfw3.h>
> > #include <glad/gl.h>
> > ```
> 
> I think we can adopt this approach. And based on this, in order not to manually define `GLFW_INCLUDE_NONE`, I think the following is better:
> 
> ```c++
> // glfw.h
> #pragma once
> 
> #ifndef GLFW_INCLUDE_NONE
> #define GLFW_INCLUDE_NONE
> #endif
> 
> #include <GLFW/glfw3.h>
> ```
> 
> It creates a new file named `glfw.h` to handle the problem.

I pushed a commit 52ae588 that should solve the problem, could you please pull it and test if the building process fails?

**Comment by CitrusSin** [comment]
Now it compiles

**Pull request closed without merging**
